eureka:
  instance:
    hostname: userserver
    # 心跳间隔
    lease-renewal-interval-in-seconds: 5
    # 服务失效时间： 如果多久没有收到请求，则可以删除服务
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: false
    eureka-service-url-poll-interval-seconds: 60
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
spring:
  application:
    name: userserver
  datasource:
    password: shineon@1234
    username: root
    url: jdbc:mysql://localhost:3306/shineon_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.shineon.userserver.entity
# 分页配置
pagehelper:
  helper-dialect: mysql
  #合理化
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com:
      shineon:
        userserver:
          dao : debug