dynDatasource:
  Address: localhost:3306
  dataBase:
    - "shineon_vms"
    - "shineon_eqm"
spring:
  datasource:
    master:
      username: root
      password: shineon@1234
      jdbc-url: jdbc:mysql://${dynDatasource.Address}/${dynDatasource.dataBase[0]}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      username: root
      password: shineon@1234
      jdbc-url: jdbc:mysql://${dynDatasource.Address}/${dynDatasource.dataBase[1]}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.shineon.pro.entity

logging:
  level:
    com:
      shineon:
        pro:
          dao : debug
